server:
  port: 8084
spring:
  application:
    name: trade-service
  cloud:
    nacos:
      server-addr: 192.168.19.130:8848
    sentinel:
      enabled: true
      http-method-specify: true
      transport:
        dashboard: localhost:10000
  rabbitmq:
    host: 192.168.19.130
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: hmall
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/hm-trade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall.trade: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 交易微服务接口文档
    description: "交易微服务接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.trade.controller
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.19.130:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: hmall
  service:
    vgroup-mapping:
      hmall: "default"
  data-source-proxy-mode: XA